version: '3.7'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: 8873025
      TELEGRAM_API_HASH: "1d169f86f42b0c37596878512f1c55af"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - 8081:8081
  bot:
    build: ./
    network_mode: host
    depends_on:
      - telegram-bot-api
    tty: true

volumes:
  telegram-bot-api-data: